import React from 'react';
import '@/styles/index.scss';
import Header from '@/components/header/header.component';
import Footer from '@/components/footer/footer.component';

export const metadata = {
  title: 'Grand',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>
          <div className="layout-main">{children}</div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
