import React from 'react';
import { Providers } from '../store/provider';
import '@/styles/index.scss';
import Header from '@/components/header/header.component';
import Footer from '@/components/footer/footer.component';

export const metadata = {
  title: {
    default: 'Grand',
    template: '%s - Grand',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          <main>
            <div className="layout-main">{children}</div>
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
